#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# https://github.com/lemofire/AutoDailyCP
# Lisence: MIT
# Author: 柠火
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

name: daily
on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: "0 4-6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download DailyCP
        run: |
          git clone https://github.com/42Sun/FuckDailyCP.git
          mv ./FuckDailyCP/* ./
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: DIY formdb
        run: |
          # 请根据日志提示的文件名修改此段代码
          cat>e341d6852fb1ca54a2df8578cfb9f99f.json<<EOF
          [{"wid": "16905", "formWid": "2592", "fieldType": 2, "title": "你目前所在校区", "description": "", "minLength": 0, "sort": "1", "maxLength": null, "isRequired": 1, "imageCount": null, "hasOtherItems": 0, "colName": "field001", "value": "", "minValue": 0.0, "maxValue": 0.0, "isDecimal": true, "fieldItems": [{"itemWid": "52761", "content": "迎西校区", "isOtherItems": 0, "contendExtend": null, "isSelected": null}, {"itemWid": "52762", "content": "虎峪校区", "isOtherItems": 0, "contendExtend": null, "isSelected": null}, {"itemWid": "52763", "content": "明向校区", "isOtherItems": 0, "contendExtend": null, "isSelected": 1}]}, {"wid": "16906", "formWid": "2592", "fieldType": 2, "title": "你目前的身体健康状况是", "description": "", "minLength": 0, "sort": "2", "maxLength": null, "isRequired": 1, "imageCount": null, "hasOtherItems": 0, "colName": "field002", "value": "", "minValue": 0.0, "maxValue": 0.0, "isDecimal": true, "fieldItems": [{"itemWid": "52764", "content": "正常", "isOtherItems": 0, "contendExtend": null, "isSelected": 1}, {"itemWid": "52765", "content": "发热或咳嗽", "isOtherItems": 0, "contendExtend": null, "isSelected": null}, {"itemWid": "52766", "content": "有其他不适症状", "isOtherItems": 0, "contendExtend": null, "isSelected": null}]}, {"wid": "16907", "formWid": "2592", "fieldType": 2, "title": "你早上7时至9时的体温是", "description": "", "minLength": 0, "sort": "3", "maxLength": null, "isRequired": 1, "imageCount": null, "hasOtherItems": 0, "colName": "field003", "value": "", "minValue": 0.0, "maxValue": 0.0, "isDecimal": true, "fieldItems": [{"itemWid": "52767", "content": "36~37.2℃", "isOtherItems": 0, "contendExtend": null, "isSelected": 1}, {"itemWid": "52768", "content": "37.3~37.9℃", "isOtherItems": 0, "contendExtend": null, "isSelected": null}, {"itemWid": "52769", "content": "38℃及以上", "isOtherItems": 0, "contendExtend": null, "isSelected": null}]}, {"wid": "16908", "formWid": "2592", "fieldType": 2, "title": "你中午11时至13时的体温是", "description": "", "minLength": 0, "sort": "4", "maxLength": null, "isRequired": 1, "imageCount": null, "hasOtherItems": 0, "colName": "field004", "value": "", "minValue": 0.0, "maxValue": 0.0, "isDecimal": true, "fieldItems": [{"itemWid": "52770", "content": "36~37.2℃", "isOtherItems": 0, "contendExtend": null, "isSelected": 1}, {"itemWid": "52771", "content": "37.3~37.9℃", "isOtherItems": 0, "contendExtend": null, "isSelected": null}, {"itemWid": "52772", "content": "38℃及以上", "isOtherItems": 0, "contendExtend": null, "isSelected": null}]}, {"wid": "16909", "formWid": "2592", "fieldType": 2, "title": "你是否做到了准确填报相关信息", "description": "", "minLength": 0, "sort": "5", "maxLength": null, "isRequired": 1, "imageCount": null, "hasOtherItems": 0, "colName": "field005", "value": "", "minValue": 0.0, "maxValue": 0.0, "isDecimal": true, "fieldItems": [{"itemWid": "52773", "content": "是", "isOtherItems": 0, "contendExtend": null, "isSelected": 1}, {"itemWid": "52774", "content": "否", "isOtherItems": 0, "contendExtend": null, "isSelected": null}]}]          
          EOF
      - name: Run program
        env:
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 DailyCP.py ${SCHOOL_NAME} ${ACCOUNT} ${PASSWORD} ${ADDRESS} ./formdb
      - name : Upload formdb
        uses: actions/upload-artifact@master
        with:
          name: formdb
          path: formdb
      - name : send notification
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }} # user id or channel name secret
          token: ${{ secrets.token }} # token secret
          status: ${{ job.status }} # do not modify this line
       
       
       
